### ISSUE TITLE
DRY

### ISSUE THREAD

**Issue by peteruithoven** [Doodle3D/Doodle3D-cura-plugin#11]
There is a lot of repetition in the current code, let's make it more [DRY](https://github.com/Doodle3D/Doodle3D-cura-plugin/). 

In `PrinterConnection.py` there are multiple calls like: 

```
Application.getInstance().getMachineManager().getActiveMachineInstance().setMachineSettingValue("machine_gcode_flavor","UltiGCode")
```

I would move that complicated call into a reusable method, like `setGCodeFlavor()`. 

When reading incoming json it's handy to store data in variables, and reuse that data through those variables. This way you only have the paths to that data in one place. Example:

``` python
printerInfo = self.printerInfo['data']
self._extTemperature = printerInfo['hotend']  # Get Extruder Temperature 
self._extTargetTemperature = printerInfo['hotend_target']  # Get Extruder Target Temperature
self._printerState = printerInfo['state']  # Get the state of the printer
self._bedTemperature = printerInfo['bed'] # Get bed temperature
self._bedTargetTemperature = printerInfo['bed_target'] # Get bed target temperature
```

Instead of:

``` python
self._extTemperature = self.printerInfo['data']['hotend']  # Get Extruder Temperature 
self._extTargetTemperature = self.printerInfo['data']['hotend_target']  # Get Extruder Target Temperature
self._printerState = self.printerInfo['data']['state']  # Get the state of the printer
self._bedTemperature = self.printerInfo['data']['bed'] # Get bed temperature
self._bedTargetTemperature = self.printerInfo['data']['bed_target'] # Get bed target temperature
```

Etc.

**Comment by Mzt-t** [comment]
> - [Added setGCodeFlavor function @ PrinterConnection.py line. 335](https://github.com/Doodle3D/Doodle3D-cura-plugin/blob/master/PrinterConnection.py#L335)
> 
> ```
> def setGCodeFlavor(self,flavor):
>     Application.getInstance().getMachineManager().getActiveMachineInstance().setMachineSettingValue("machine_gcode_flavor",flavor)
>     return
> ```
> 
> > - [Added forceSlice function @ PrinterConnection.py line. 339](https://github.com/Doodle3D/Doodle3D-cura-plugin/blob/master/PrinterConnection.py#L339)
> > 
> > ```
> > def forceSlice(self):
> >     Application.getInstance().getBackend().forceSlice()
> >     return
> > ```
> > 
> > > - [Printer data variable names are now 'DRY' @ PrinterConnection.py line. 343](https://github.com/Doodle3D/Doodle3D-cura-plugin/blob/master/PrinterConnection.py#L343)
> > > 
> > > ```
> > > self.printerInfo = self.printerInfo['data']
> > > ```
