### ISSUE TITLE
When buffer full, delay before retry?

### ISSUE THREAD

**Issue by peteruithoven** [Doodle3D/Doodle3D-cura-plugin#13]
If I understand the `printGCode` logic there is no delay after it detects the buffer is full, this means it would retry this as fast as possible. Shouldn't we add a little delay here?

**Comment by Mzt-t** [comment]
[Added 3 seconds delay for keeping buffered lines in check. @ PrinterConnection.py line. 232](https://github.com/Doodle3D/Doodle3D-cura-plugin/blob/master/PrinterConnection.py#L232)

**Comment by peteruithoven** [comment]
But now it always adds a 3 second delay between sending print parts?

**Comment by Mzt-t** [comment]
Couldn't I just delete the time.sleep here: https://github.com/Doodle3D/Doodle3D-cura-plugin/blob/master/PrinterConnection.py#L232
Since https://github.com/Doodle3D/Doodle3D-cura-plugin/blob/master/PrinterConnection.py#L227 does the job now?

**Comment by peteruithoven** [comment]
You could, but I can imagine you want to use different timeout times for those.

**Comment by Mzt-t** [comment]
This should fix that:
https://github.com/Doodle3D/Doodle3D-cura-plugin/blob/master/PrinterConnection.py#L232

**Comment by peteruithoven** [comment]
I think that makes sense.
