### ISSUE TITLE
Menubar entry

### ISSUE THREAD

**Issue by mith** [Doodle3D/Doodle3D-cura-plugin#32]
The other downloadable plugins have an entry in the menubar under "Extensions". Maybe we could list recent exports there, allowing users to open Doodle3D Connect at a later time?

**Comment by companje** [comment]
I think that's a good idea.

<img width="665" alt="screen shot 2017-08-21 at 15 25 21" src="https://user-images.githubusercontent.com/156066/29521274-1a658632-8685-11e7-954b-b9461ca5b6c2.png">

**Comment by mith** [comment]
Adding a sub-submenu doesn't seem to be possible, so i added an "Open Doodle3D Connect" menu item.
<img width="520" alt="screen shot 2017-08-22 at 12 20 46" src="https://user-images.githubusercontent.com/33195/29561070-705a59f0-8734-11e7-86a8-6c4f0e4bbced.png">

Closing this issue for now
