### ISSUE TITLE
Show feedback when lost connection to WiFi-Box

### ISSUE THREAD

**Issue by peteruithoven** [Doodle3D/Doodle3D-cura-plugin#8]
Currently no feedback is shown when the connection to the WiFi-Box is lost. We probably also want to disable all the buttons in that situation.

**Comment by Mzt-t** [comment]
Fixed here: 
https://github.com/Doodle3D/Doodle3D-cura-plugin/blob/master/PrinterConnection.py#L320

**Comment by peteruithoven** [comment]
That handles a different issue? that the WiFi-Box isn't connected to a printer.
